export const employeeData = [
  {
    name: 'Margo Keith',
    age: 22,
    eyeColor: 'blue',
    company: 'Quailcom',
    phone: '+1 (932) 468-3131',
    teamMembers: [
      {
        name: 'Tabitha Gilbert',
        age: 32,
        eyeColor: 'blue',
        company: 'Elemantra',
        phone: '+1 (992) 495-3166',
      },
      {
        name: 'Medina Wolfe',
        age: 24,
        eyeColor: 'green',
        company: 'Krog',
        phone: '+1 (917) 406-2065',
      },
      {
        name: 'Alana Medina',
        age: 31,
        eyeColor: 'green',
        company: 'Locazone',
        phone: '+1 (800) 549-3555',
      },
      {
        name: 'Priscilla Beasley',
        age: 30,
        eyeColor: 'blue',
        company: 'Corpulse',
        phone: '+1 (837) 466-3544',
      },
    ],
  },
  {
    name: 'Benita Bartlett',
    age: 37,
    eyeColor: 'brown',
    company: 'Talkola',
    phone: '+1 (813) 580-3584',
    teamMembers: [
      {
        name: 'Mcconnell Rowe',
        age: 29,
        eyeColor: 'brown',
        company: 'Quonata',
        phone: '+1 (847) 582-3810',
      },
      {
        name: 'Sharpe Merrill',
        age: 26,
        eyeColor: 'green',
        company: 'Mediot',
        phone: '+1 (800) 503-2341',
      },
      {
        name: 'Casandra Wilcox',
        age: 39,
        eyeColor: 'brown',
        company: 'Vixo',
        phone: '+1 (820) 434-2487',
      },
      {
        name: 'Sexton Mcfarland',
        age: 36,
        eyeColor: 'brown',
        company: 'Rodemco',
        phone: '+1 (909) 549-3652',
      },
      {
        name: 'Ericka Snyder',
        age: 33,
        eyeColor: 'brown',
        company: 'Twiist',
        phone: '+1 (967) 568-3798',
      },
    ],
  },
  {
    name: 'Jerry Vasquez',
    age: 32,
    eyeColor: 'green',
    company: 'Namebox',
    phone: '+1 (829) 459-3171',
    teamMembers: [
      {
        name: 'Cora Rodriquez',
        age: 35,
        eyeColor: 'brown',
        company: 'Rodeomad',
        phone: '+1 (872) 432-2678',
      },
      {
        name: 'Lizzie Curry',
        age: 29,
        eyeColor: 'green',
        company: 'Eclipto',
        phone: '+1 (912) 416-3367',
      },
      {
        name: 'Harris Scott',
        age: 33,
        eyeColor: 'brown',
        company: 'Petigems',
        phone: '+1 (895) 540-2185',
      },
      {
        name: 'Angelica Casey',
        age: 30,
        eyeColor: 'blue',
        company: 'Imageflow',
        phone: '+1 (812) 487-3167',
      },
      {
        name: 'Nicholson Sharpe',
        age: 31,
        eyeColor: 'green',
        company: 'Pharmacon',
        phone: '+1 (880) 402-2638',
      },
    ],
  },
  {
    name: 'Bowers Alexander',
    age: 30,
    eyeColor: 'brown',
    company: 'Xeronk',
    phone: '+1 (882) 405-2932',
    teamMembers: [
      {
        name: 'Estes Le',
        age: 22,
        eyeColor: 'green',
        company: 'Perkle',
        phone: '+1 (962) 479-2819',
      },
      {
        name: 'Franco Mercer',
        age: 37,
        eyeColor: 'brown',
        company: 'Orbin',
        phone: '+1 (931) 438-3586',
      },
      {
        name: 'Jamie Mathis',
        age: 24,
        eyeColor: 'brown',
        company: 'Repetwire',
        phone: '+1 (805) 534-3848',
      },
      {
        name: 'Hallie Fischer',
        age: 23,
        eyeColor: 'green',
        company: 'Electonic',
        phone: '+1 (867) 572-3036',
      },
    ],
  },
  {
    name: 'Townsend Gonzalez',
    age: 35,
    eyeColor: 'blue',
    company: 'Boink',
    phone: '+1 (826) 510-2564',
    teamMembers: [
      {
        name: 'Hewitt Morin',
        age: 32,
        eyeColor: 'blue',
        company: 'Jetsilk',
        phone: '+1 (805) 480-3613',
      },
      {
        name: 'Gonzalez Greene',
        age: 27,
        eyeColor: 'blue',
        company: 'Zytrac',
        phone: '+1 (847) 522-2686',
      },
      {
        name: 'Ollie Workman',
        age: 22,
        eyeColor: 'brown',
        company: 'Animalia',
        phone: '+1 (806) 461-3543',
      },
      {
        name: 'Vera Watson',
        age: 20,
        eyeColor: 'brown',
        company: 'Xanide',
        phone: '+1 (982) 490-2936',
      },
      {
        name: 'Deloris Kinney',
        age: 32,
        eyeColor: 'brown',
        company: 'Geekular',
        phone: '+1 (808) 442-3694',
      },
      {
        name: 'Tamera Mitchell',
        age: 26,
        eyeColor: 'blue',
        company: 'Zepitope',
        phone: '+1 (832) 564-3160',
      },
      {
        name: 'Bryant Rice',
        age: 39,
        eyeColor: 'blue',
        company: 'Exostream',
        phone: '+1 (855) 440-2291',
      },
      {
        name: 'Beach Hampton',
        age: 23,
        eyeColor: 'blue',
        company: 'Reversus',
        phone: '+1 (887) 527-3918',
      },
    ],
  },
];

export const columns = [
  {
    label: 'name',
    value: 'name',
  },
  {
    label: 'age',
    value: 'age',
  },
  {
    label: 'eye color',
    value: 'eyeColor',
  },
  {
    label: 'company',
    value: 'company',
  },
  {
    label: 'mobile',
    value: 'phone',
  },
];
