export const employeeData = [
  {
    id: '5eabd6746461ccc954a9ecb7',
    name: 'Adela Robertson',
    age: 37,
    eyeColor: 'green',
    company: 'GINKOGENE',
    phone: '+1 (919) 429-3934',
    teamMembers: [
      {
        name: 'Potter Gonzalez',
        age: 34,
        eyeColor: 'green',
        company: 'AEORA',
        phone: '+1 (902) 486-3232',
      },
      {
        name: 'Miranda Mcfarland',
        age: 39,
        eyeColor: 'blue',
        company: 'EWEVILLE',
        phone: '+1 (975) 465-2544',
      },
      {
        name: 'Dollie Turner',
        age: 23,
        eyeColor: 'blue',
        company: 'XEREX',
        phone: '+1 (956) 516-2672',
      },
      {
        name: 'Foster Glass',
        age: 34,
        eyeColor: 'green',
        company: 'VORATAK',
        phone: '+1 (852) 599-3669',
      },
    ],
  },
  {
    id: '5eabd674ebf11bd6f37ffe35',
    name: 'Church Short',
    age: 38,
    eyeColor: 'brown',
    company: 'DIGIRANG',
    phone: '+1 (857) 565-2054',
    teamMembers: [
      {
        name: 'Tate Farmer',
        age: 24,
        eyeColor: 'blue',
        company: 'FURNIGEER',
        phone: '+1 (893) 518-2843',
      },
      {
        name: 'Mabel Pace',
        age: 34,
        eyeColor: 'green',
        company: 'ZIALACTIC',
        phone: '+1 (871) 560-3963',
      },
      {
        name: 'Henson Duncan',
        age: 36,
        eyeColor: 'green',
        company: 'GEOFORMA',
        phone: '+1 (829) 580-2289',
      },
      {
        name: 'Rose Roberts',
        age: 34,
        eyeColor: 'blue',
        company: 'CALLFLEX',
        phone: '+1 (940) 550-2435',
      },
      {
        name: 'Kayla Hyde',
        age: 40,
        eyeColor: 'blue',
        company: 'THREDZ',
        phone: '+1 (852) 500-2825',
      },
      {
        name: 'Queen Cruz',
        age: 31,
        eyeColor: 'brown',
        company: 'VIASIA',
        phone: '+1 (884) 495-3349',
      },
      {
        name: 'Riley Cross',
        age: 26,
        eyeColor: 'brown',
        company: 'SKYPLEX',
        phone: '+1 (947) 444-3680',
      },
    ],
  },
  {
    id: '5eabd67498ee8b05b1f277f6',
    name: 'Woodward Ward',
    age: 37,
    eyeColor: 'green',
    company: 'VELOS',
    phone: '+1 (986) 426-2037',
    teamMembers: [
      {
        name: 'Carver Roach',
        age: 26,
        eyeColor: 'brown',
        company: 'GLUID',
        phone: '+1 (998) 475-3693',
      },
      {
        name: 'Cruz Parrish',
        age: 25,
        eyeColor: 'brown',
        company: 'ULTRIMAX',
        phone: '+1 (824) 500-2853',
      },
      {
        name: 'Myers Taylor',
        age: 39,
        eyeColor: 'brown',
        company: 'XIXAN',
        phone: '+1 (802) 413-3376',
      },
      {
        name: 'Bolton Newman',
        age: 32,
        eyeColor: 'brown',
        company: 'ZILPHUR',
        phone: '+1 (952) 451-3014',
      },
      {
        name: 'Abby Pennington',
        age: 27,
        eyeColor: 'blue',
        company: 'GEEKMOSIS',
        phone: '+1 (926) 477-3625',
      },
    ],
  },
  {
    id: '5eabd6743af3ac3908d31456',
    name: 'Hebert Preston',
    age: 29,
    eyeColor: 'blue',
    company: 'ZERBINA',
    phone: '+1 (964) 404-3215',
    teamMembers: [
      {
        name: 'Beck Valenzuela',
        age: 28,
        eyeColor: 'brown',
        company: 'INTERODEO',
        phone: '+1 (855) 546-3650',
      },
      {
        name: 'Kline Mendez',
        age: 20,
        eyeColor: 'brown',
        company: 'HOMELUX',
        phone: '+1 (950) 580-3934',
      },
      {
        name: 'Esperanza Lindsay',
        age: 37,
        eyeColor: 'blue',
        company: 'FORTEAN',
        phone: '+1 (871) 460-2039',
      },
      {
        name: 'Liliana Schwartz',
        age: 34,
        eyeColor: 'blue',
        company: 'OPTIQUE',
        phone: '+1 (876) 518-3008',
      },
    ],
  },
  {
    id: '5eabd674a978fec7917cc0d7',
    name: 'Janette Raymond',
    age: 37,
    eyeColor: 'brown',
    company: 'ECRATER',
    phone: '+1 (900) 465-3279',
    teamMembers: [
      {
        name: 'Mckay Acevedo',
        age: 33,
        eyeColor: 'brown',
        company: 'ROUGHIES',
        phone: '+1 (920) 594-3322',
      },
      {
        name: 'Nora Sweet',
        age: 34,
        eyeColor: 'brown',
        company: 'KOOGLE',
        phone: '+1 (808) 418-2684',
      },
      {
        name: 'Alexander Bush',
        age: 37,
        eyeColor: 'blue',
        company: 'PLASMOS',
        phone: '+1 (949) 447-2878',
      },
      {
        name: 'Hewitt Baird',
        age: 32,
        eyeColor: 'green',
        company: 'DOGSPA',
        phone: '+1 (952) 566-2304',
      },
      {
        name: 'Barton Flores',
        age: 28,
        eyeColor: 'blue',
        company: 'ILLUMITY',
        phone: '+1 (844) 586-3638',
      },
      {
        name: 'Nina Randolph',
        age: 38,
        eyeColor: 'green',
        company: 'STRALOY',
        phone: '+1 (932) 425-2643',
      },
    ],
  },
];

export const columns = [
  {
    label: 'name',
    value: 'name',
  },
  {
    label: 'age',
    value: 'age',
  },
  {
    label: 'eye color',
    value: 'eyeColor',
  },
  {
    label: 'company',
    value: 'company',
  },
  {
    label: 'mobile',
    value: 'phone',
  },
];
